name: Build Backend & Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias del backend
        working-directory: ./backend
        run: npm install

      - name: Instalar dependencias del frontend
        working-directory: ./frontend
        run: npm install

      - name: Compilar frontend
        working-directory: ./frontend
        run: npm run build
