name: Deploy Backend to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias del backend
        working-directory: ./backend
        run: npm install

      - name: Comprimir backend
        run: |
          cd ..
          zip -r backend.zip backend -x "backend/node_modules/*"

      - name: Desplegar a Azure con Zip Deploy
        run: |
          curl -X POST "https://${{ secrets.AZURE_WEBAPP_BACKEND_NAME }}.scm.azurewebsites.net/api/zipdeploy" \
          -u ${{ secrets.AZURE_WEBAPP_BACKEND_PUBLISH_PROFILE }} \
          --data-binary @"backend.zip"
