name: Run Backend Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias del backend
        working-directory: ./backend
        run: npm install

      - name: Ejecutar pruebas
        working-directory: ./backend
        run: npm test
